<?php

/**
 * PluginpbAssignedMediaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpbAssignedMediaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginpbAssignedMediaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpbAssignedMedia');
    }
}