<?php

/**
 * PluginImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpbImageTable extends pbMediaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginpbImageTable PluginpbImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpbImage');
    }

}