<?php

/**
 * PluginMedia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginpbMedia extends BasepbMedia
{
    //ta metoda powinna byc w aplikacji a nie w pluginie. Powod ten sam jak
    //w PluginpbImage::bulkDeleteFiles
//    static public function bulkDeleteFiles($filenames)
//    {
//        pbFile::deleteFiles(sfConfig::get('app_pb_upload_dir'), $filenames);
//    }

    public function getModelName()
    {
        $assigned_media = $this->getPbAssignedMedia();

        return $assigned_media ? $assigned_media->getModelName() : null ;
    }

    public function getRelatedRecord()
    {
        $assigned_media = $this->getPbAssignedMedia();
        return $assigned_media ? $assigned_media->getRelatedRecord() : null ;
    }

    /**
    * Psychically deletes related file
    * @param Doctrine_Connection $conn
    * @return <type>
    */
    public function delete(Doctrine_Connection $conn = null)
    {
        $deleted = parent::delete();

        //delete related file
        if($deleted)
        {
            $this->deleteFile();
        }

        return $deleted;
    }

    public function deleteFile()
    {
        @unlink($this->getPath());
    }

    public function getPath()
    {
        return $this->getFileDir().DIRECTORY_SEPARATOR.$this->getFileName();
    }

    public function getWebPath()
    {
        return self::toWebPath($this->getPath());
    }

    static public function toWebPath($system_path)
    {
        return substr($system_path, strlen(sfConfig::get('sf_web_dir')) - strlen($system_path));
    }
    
    public function getFileTypeMapped()
    {
        return FileTypeMapper::getMapping($this->getFileType());
    }

    static public function mediaDir()
    {
        return sfConfig::get('app_pb_media_upload_dir');
    }

}